version: '3.8'
services:
  pr_db:
    image: postgres
    container_name: pr-postgres-db 
    environment:
      POSTGRES_USER: ${PR_DB_USER:-admin}
      POSTGRES_PASSWORD: ${PR_DB_PASSWORD:-pass}
      POSTGRES_DB: ${PR_DB_NAME:-pr_db}
    ports:
      - ${PR_DB_PORT:-5432}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  setup:
    build: .
    depends_on:
      - pr_db
    environment:
      PR_DB_USER: ${PR_DB_USER:-admin}
      PR_DB_PASSWORD: ${PR_DB_PASSWORD:-pass}
      PR_DB_NAME: ${PR_DB_NAME:-pr_db}
      PR_DB_HOST: pr_db
      PR_DB_PORT: ${PR_DB_PORT:-5432}
    volumes:
      - .:/app
    working_dir: /app
    command: ["./setup/wait-for-it.sh", "pr_db", "5432", "--", "python", "setup/setup_pr.py"]
  app:
    build: .
    depends_on:
      - setup
    environment:
      PR_DB_USER: ${PR_DB_USER:-admin}
      PR_DB_PASSWORD: ${PR_DB_PASSWORD:-pass}
      PR_DB_NAME: ${PR_DB_NAME:-pr_db}
      PR_DB_HOST: pr_db
      PR_DB_PORT: ${PR_DB_PORT:-5432}
      FLASK_RUN_HOST: ${FLASK_RUN_HOST:-0.0.0.0}
      FLASK_RUN_PORT: ${FLASK_RUN_PORT:-5000}
    ports:
      - ${FLASK_RUN_PORT:-5000}:5000
    volumes:
      - .:/app
    working_dir: /app
    command: python src/app.py

volumes:
  pgdata: